//
// Created by larr-desktop on 22. 10. 21.
//

#ifndef WHEELCHAIR_PLANNER_CONNECTEDBODYPLANNER_H
#define WHEELCHAIR_PLANNER_CONNECTEDBODYPLANNER_H

#endif //WHEELCHAIR_PLANNER_CONNECTEDBODYPLANNER_H
